format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
style = "bold cyan"
format = "[\uf07c $path]($style) "

[git_branch]
symbol = "\uf418 "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style)) "
conflicted = "\uf071 "
ahead = "\uf062 ${count}"
behind = "\uf063 ${count}"
diverged = "⇕ ${count}"
untracked = "\uf128 ${count}"
stashed = "\uf0c7 ${count}"
modified = "\uf040 ${count}"
staged = "\uf067 ${count}"
renamed = "\uf074 ${count}"
deleted = "\uf014 ${count}"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

[nodejs]
[python]
[rust]
[golang]
